databases:
  - name: lesslysflowersinventoryapp
    databaseName: lesslysflowersinventoryapp
    user: lesslysflowersinventoryapp

services:
  - type: web
    name: lesslysflowersinventoryapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn lesslysflowersinventoryapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lesslysflowersinventoryapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: "3.11.5"
