databases:
  - name: flowersinventory
    databaseName: flowersinventory
    user: flowersinventory

services:
  - type: web
    name: flowersinventory
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn flowersinventory.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flowersinventory
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4