# Generated by Django 3.2.19 on 2023-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceImport', '0017_alter_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
