# Generated by Django 3.2.19 on 2023-07-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceImport', '0005_alter_product_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('bunch', 'Bunch'), ('stem', 'Stem')], default='bunch', max_length=50),
        ),
    ]
