# Generated by Django 3.2.19 on 2023-07-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceImport', '0009_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='invoice_total',
        ),
    ]
