# Generated by Django 3.2.19 on 2023-07-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceImport', '0013_auto_20230725_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceproducts',
            old_name='quantity',
            new_name='total_units',
        ),
    ]
