# Generated by Django 3.2.19 on 2023-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceImport', '0014_rename_quantity_invoiceproducts_total_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproducts',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
    ]
